### ISSUE TITLE
`favlist sub`

### ISSUE THREAD

**Issue by spenserblack** [spenserblack/favlist#4]
`favlist sub <list name> <row ID>`
- [ ] Implement with row ID passed via CLI #15 
- [ ] Show preview and prompt for row ID otherwise #15 
- [ ] Use `--filter` to remove a group of matching rows #15
